on: 
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Version
        uses: paulhatch/semantic-version@v4.0.2
        id: generate_version
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}"
          short_tags: true
          bump_each_commit: true
        
      - name: echo info
        run: echo "Got version ${{ steps.generate_version.outputs.version }}"
        
      - name: Generate Changelog
        uses: Bullrich/generate-release-changelog@master
        id: generate_changelog
        env:
          REPO: ${{ github.repository }}
          
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.generate_version.outputs.version }}
          tag_name: ${{ steps.generate_version.outputs.version_tag }}
          body: ${{ steps.generate_changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - uses: papeloto/action-zip@v1
        with:
          files: test.txt
          dest: result.zip
          
      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: result.zip
          asset_name: artifact.zip
          asset_content_type: application/zip
