name: Test on feature branch

on:
  push:
    branches: [ feature/* ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout Modules
      uses: actions/checkout@v2
      with:
        submodules: true
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install Dependencies
      run: dotnet restore

    - name: Execute Tests
      run: dotnet test --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      continue-on-error: true

    - name: Upload Coverage
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
