name: Test & Create Release on main

on: 
  push:
    branches: [ main ]

jobs:
  release:
    name: Build, Test & Create Release
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Modules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
   
      - name: Install Dependencies
        run: dotnet restore

      - name: Execute Tests
        run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    
      - name: Upload Coverage
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Generate Tag Version
        id: tag_version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Generate Changelog
        uses: mikepenz/release-changelog-builder-action@v2.6.0
        id: generate_changelog
        with:
         commitMode: true
         configuration: changelog-config.json

      - name: Publish Solution
        run: dotnet publish ${{ github.event.repository.name }}/${{ github.event.repository.name }}.csproj -c Release -r win-x64 -p:PublishSingleFile=true --sc true -o Publish -p:Version=${{ steps.tag_version.outputs.tag }}

      - name: Zip Artifact
        run: (cd Publish; zip -r ../${{ github.event.repository.name }}-v${{ steps.tag_version.outputs.tag }}.zip .)

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.event.repository.name }}-v${{ steps.tag_version.outputs.tag }}.zip
          tag_name: v${{ steps.tag_version.outputs.tag }}
          name: ${{ github.event.repository.name }}-v${{ steps.tag_version.outputs.tag }}
          body: ${{ steps.generate_changelog.outputs.changelog }}
