on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Modules
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
   
      - name: Install Dependencies
        run: dotnet restore

      - name: Tag Version
        uses: paulhatch/semantic-version@v4.0.2
        id: generate_version
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}"
          short_tags: true
          bump_each_commit: true
        
      - name: Publish Solution
        run: dotnet publish ActionsSandbox/ActionsSandbox.csproj -c Release -r win-x64 -p:PublishSingleFile=true --sc true -o Publish -p:Version=${{ steps.generate_version.outputs.version }}

      - name: echo info
        run: echo "Got version ${{ steps.generate_version.outputs.version }}"
        
      - name: Generate Changelog
        uses: mikepenz/release-changelog-builder-action@v1
        id: generate_changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.generate_version.outputs.version }}
          tag_name: ${{ steps.generate_version.outputs.version_tag }}
          body: ${{ steps.generate_changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: Zip Artifact
        run: Compress-Archive -Path Publish -DestinationPath artifact.zip
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifact.zip
          