name: tag - Create Release

on:
  push:
    tags: [v*]

jobs:
  release:
    name: Build & Create Release
    runs-on: windows-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Modules
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Install Dependencies
        run: dotnet restore

      - name: Get Latest Tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        id: latest_tag

      - name: Strip V From Tag
        uses: actions/github-script@v4
        id: latest_tag_no_v
        with:
          script: core.setOutput('tag_no_v', '${{ steps.latest_tag.outputs.tag }}'.replace('v', ''))

      - name: Generate Changelog
        uses: mikepenz/release-changelog-builder-action@v2.6.0
        id: generate_changelog
        with:
          commitMode: true
          configuration: changelog-config.json

      - name: Publish Solution
        run: >
          dotnet publish ${{ github.event.repository.name }}/${{ github.event.repository.name }}.csproj
          -c Release -r win-x64 -p:PublishSingleFile=true --sc true -o Publish -p:Version=${{ steps.latest_tag_no_v.outputs.tag_no_v }}

      - name: Zip Artifact
        run: Compress-Archive -Path Publish/* -DestinationPath ${{ github.event.repository.name }}-${{ steps.latest_tag.outputs.tag }}.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.event.repository.name }}-${{ steps.latest_tag.outputs.tag }}.zip
          name: ${{ github.event.repository.name }}-${{ steps.latest_tag.outputs.tag }}
          body: ${{ steps.generate_changelog.outputs.changelog }}
