on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Modules
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
   
      - name: Install Dependencies
        run: dotnet restore

      - name: Generate Tag Version
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Changelog
        uses: mikepenz/release-changelog-builder-action@v2.6.0
        id: generate_changelog
        with:
         commitMode: true
         configuration: changelog-config.json

      - name: Publish Solution
        run: dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --sc true -o Publish -p:Version=${{ steps.tag_version.outputs.new_version }}

      - name: Zip Artifact
        run: Compress-Archive -Path Publish/* -DestinationPath ${{ github.event.repository.name }}-${{ steps.tag_version.outputs.new_tag }}.zip
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.event.repository.name }}-${{ steps.tag_version.outputs.new_tag }}.zip
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ github.event.repository.name }}-${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.generate_changelog.outputs.changelog }}